server_adress : ":8080"
dataBase_url : "root:modano24@tcp(localhost:3306)/movies_db"
apiMovies_access_token : "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2ZjIwZjVkNjM0NjA5NDlkM2Y5YWY3MDI2NjEyMjhiNyIsIm5iZiI6MTcyNDAxNzgyMC45NTE2ODMsInN1YiI6IjY2YzI2N2QwOWEwNzhjNTVjYjVkNmVhYSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.mnrz8JV1sr0H8nonknRgxnxnDqrug6SLL4aQ3-fbJZQ"
jwt_secret_key : "secreto"